parameters:
    database_driver:   pdo_pgsql
    database_host:     localhost
    database_port:     5432
    database_name:     symfony_hangman
    database_user:     paul
    database_password: 

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt